export const PLAN_PAYMENT_SIGNUP = "PLAN_PAYMENT_SIGNUP";
export const PLAN_PAYMENT_SIGNUP_SUCCESS = "PLAN_PAYMENT_SIGNUP_SUCCESS";
export const PLAN_PAYMENT_SIGNUP_FAILED  = "PLAN_PAYMENT_SIGNUP_FAILED";