export const SIGNUP_BUSINESS_PROFILE = "SIGNUP_BUSINESS_PROFILE";
export const SIGNUP_BUSINESS_PROFILE_SUCCESS = "SIGNUP_BUSINESS_PROFILE_SUCCESS";
export const SIGNUP_BUSINESS_PROFILE_FAILED  = "SIGNUP_BUSINESS_PROFILE_FAILED";