export const GET_MUSICAL_GENRE = "GET_MUSICAL_GENRE";
export const GET_MUSICAL_GENRE_SUCCESS = "GET_MUSICAL_GENRE_SUCCESS";
export const GET_MUSICAL_GENRE_FAILED  = "GET_MUSICAL_GENRE_FAILED";



export const SIGNUP_MUSICAL_GENRE = "SIGNUP_MUSICAL_GENRE";
export const SIGNUP_MUSICAL_GENRE_SUCCESS = "SIGNUP_MUSICAL_GENRE_SUCCESS";
export const SIGNUP_MUSICAL_GENRE_FAILED  = "SIGNUP_MUSICAL_GENRE_FAILED";


