export const PAYMENT_METHOD_SIGNUP = "PAYMENT_METHOD_SIGNUP";
export const PAYMENT_METHOD_SIGNUP_SUCCESS = "PAYMENT_METHOD_SIGNUP_SUCCESS";
export const PAYMENT_METHOD_SIGNUP_FAILED  = "PAYMENT_METHOD_SIGNUP_FAILED";