export const GET_EVENT = "GET_EVENT";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILED = "GET_EVENT_FAILED";

export const SIGNUP_EVENT = "SIGNUP_EVENT";
export const SIGNUP_EVENT_SUCCESS = "SIGNUP_EVENT_SUCCESS";
export const SIGNUP_EVENT_FAILED = "SIGNUP_EVENT_FAILED";

