export const GET_RESERVATION = "GET_RESERVATION";
export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS";
export const GET_RESERVATION_FAILED = "GET_RESERVATION_FAILED";

export const SIGNUP_RESERVATION = "SIGNUP_RESERVATION";
export const SIGNUP_RESERVATION_SUCCESS = "SIGNUP_RESERVATION_SUCCESS";
export const SIGNUP_RESERVATION_FAILED = "SIGNUP_RESERVATION_FAILED";

